from db.database import get_supabase

def seed_actions():
    supabase = get_supabase()

    actions = [
        {
            "id": 1,
            "title": "Take 3 deep breaths",
            "type": "breathing",
            "description": "Slow your breathing and relax your body.",
            "duration_sec": 60,
            "difficulty": 1,
            "is_premium": False,
            "is_active": True,
            "recommended_for": None,
        },
        {
            "id": 2,
            "title": "Write a gratitude note",
            "type": "gratitude",
            "description": "Write down one thing you are grateful for today.",
            "duration_sec": 180,
            "difficulty": 1,
            "is_premium": False,
            "is_active": True,
            "recommended_for": None,
        },
        {
            "id": 3,
            "title": "Take a walk",
            "type": "walking",
            "description": "Take a short walk and let your body reset.",
            "duration_sec": 600,
            "difficulty": 1,
            "is_premium": False,
            "is_active": True,
            "recommended_for": None,
        },
        {
            "id": 4,
            "title": "Listen to music",
            "type": "music",
            "description": "Listen to one song that fits your mood.",
            "duration_sec": 300,
            "difficulty": 1,
            "is_premium": False,
            "is_active": True,
            "recommended_for": None,
        },
        {
            "id": 5,
            "title": "Write down your feelings",
            "type": "journal",
            "description": "Write a few lines about what you are feeling.",
            "duration_sec": 600,
            "difficulty": 2,
            "is_premium": False,
            "is_active": True,
            "recommended_for": None,
        },
        {
            "id": 6,
            "title": "Drink some water",
            "type": "drink_water",
            "description": "Slowly drink a glass of water.",
            "duration_sec": 120,
            "difficulty": 1,
            "is_premium": False,
            "is_active": True,
            "recommended_for": None,
        },
        {
            "id": 7,
            "title": "Stretch your body",
            "type": "stretching",
            "description": "Gently stretch your shoulders, arms, and back.",
            "duration_sec": 300,
            "difficulty": 1,
            "is_premium": False,
            "is_active": True,
            "recommended_for": None,
        },
        {
            "id": 8,
            "title": "Take a short break",
            "type": "rest",
            "description": "Pause for a few minutes and let yourself rest.",
            "duration_sec": 300,
            "difficulty": 1,
            "is_premium": False,
            "is_active": True,
            "recommended_for": None,
        },
        {
            "id": 9,
            "title": "Get some sunlight",
            "type": "sunlight",
            "description": "Spend a few minutes near a window or outside.",
            "duration_sec": 300,
            "difficulty": 1,
            "is_premium": False,
            "is_active": True,
            "recommended_for": None,
        },
        {
            "id": 10,
            "title": "Take a warm shower",
            "type": "warm_shower",
            "description": "Take a warm shower and give yourself a reset.",
            "duration_sec": 600,
            "difficulty": 1,
            "is_premium": False,
            "is_active": True,
            "recommended_for": None,
        },
        {
            "id": 11,
            "title": "Reach out to someone",
            "type": "contact_someone",
            "description": "Send a short message to someone you trust.",
            "duration_sec": 300,
            "difficulty": 1,
            "is_premium": False,
            "is_active": True,
            "recommended_for": None,
        },
        {
            "id": 12,
            "title": "Have a tea break",
            "type": "tea_break",
            "description": "Slow down with a warm drink for a few minutes.",
            "duration_sec": 300,
            "difficulty": 1,
            "is_premium": False,
            "is_active": True,
            "recommended_for": None,
        },
        {
            "id": 13,
            "title": "Scream into a pillow",
            "type": "pillow_scream",
            "description": "Press your face into a pillow and let out a short scream.",
            "duration_sec": 3,
            "difficulty": 1,
            "is_premium": False,
            "is_active": True,
            "recommended_for": None,
        },
    ]

    for action in actions:
        supabase.table("actions").upsert(action).execute()

if __name__ == "__main__":
    seed_actions()
